/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: 1f831eb8a4521e9b5d36f03404b0f84a)
interface __BaseEnv_Env {
	VIDEO_MEDIA: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	ORANGE_API_BASE: "https://api.orangeapi.chat/v1";
	ORANGE_MODEL: "seedance-2-5";
	ORANGE_DURATION_SECONDS: "10";
	ORANGE_RESOLUTION: "720P";
	ORANGE_RATIO: "16:9";
	ORANGE_WATERMARK: "true";
	VIDEO_BUFFER_TARGET: "8";
	VIDEO_ARCHIVE_LIMIT: "100";
	CHAT_SNAPSHOT_LIMIT: "60";
	CHAT_PAGE_LIMIT: "100";
	MAX_PAID_GENERATIONS_PER_DAY: "100";
	CHANNEL_BOT_ENABLED: "true";
	CHANNEL_BOT_INTERVAL_MINUTES: "10";
	VIDEO_WORKFLOW: Workflow<Parameters<import("./index").VideoGenerationWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORANGE_API_BASE" | "ORANGE_MODEL" | "ORANGE_DURATION_SECONDS" | "ORANGE_RESOLUTION" | "ORANGE_RATIO" | "ORANGE_WATERMARK" | "VIDEO_BUFFER_TARGET" | "VIDEO_ARCHIVE_LIMIT" | "CHAT_SNAPSHOT_LIMIT" | "CHAT_PAGE_LIMIT" | "MAX_PAID_GENERATIONS_PER_DAY" | "CHANNEL_BOT_ENABLED" | "CHANNEL_BOT_INTERVAL_MINUTES">> {}
}
