/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: fb48bfdd77500f5f43bcbfd22ab720fc)
interface __BaseEnv_Env {
	VIDEO_MEDIA: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	ORANGE_API_BASE: "https://api.orangeapi.chat/v1";
	ORANGE_MODEL: "wan2.7-t2v";
	ORANGE_DURATION_SECONDS: "10";
	ORANGE_RESOLUTION: "720P";
	GROK_RESOLUTION: "480P";
	ORANGE_RATIO: "16:9";
	ORANGE_WATERMARK: "true";
	TEXT_POLISH_API_BASE: "https://ai-cpa-cf.nullatoms.com/v1";
	TEXT_POLISH_MODEL: "gpt-5.4-mini";
	TEXT_POLISH_ENABLED: "true";
	VIDEO_BUFFER_TARGET: "3";
	VIDEO_ARCHIVE_LIMIT: "500";
	PLAYBACK_RECENCY_WINDOW: "48";
	CHAT_SNAPSHOT_LIMIT: "40";
	CHAT_PAGE_LIMIT: "100";
	QUEUE_SNAPSHOT_LIMIT: "24";
	MAX_PAID_GENERATIONS_PER_DAY: "12";
	MAX_CONCURRENT_GENERATIONS: "1";
	GENERATION_POLL_INTERVAL_SECONDS: "300";
	CHANNEL_BOT_ENABLED: "false";
	CHANNEL_BOT_GROK_ENABLED: "false";
	CHANNEL_BOT_FREE_MODEL: "agnes-video-v2.0";
	CHANNEL_BOT_FREE_MODEL_EVERY: "1";
	CHANNEL_BOT_INTERVAL_MINUTES: "10";
	CHANNEL_BOT_QUEUE_TARGET: "2";
	D1_EMERGENCY_READONLY_UNTIL: "2026-09-04T00:00:00.000Z";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORANGE_API_BASE" | "ORANGE_MODEL" | "ORANGE_DURATION_SECONDS" | "ORANGE_RESOLUTION" | "GROK_RESOLUTION" | "ORANGE_RATIO" | "ORANGE_WATERMARK" | "TEXT_POLISH_API_BASE" | "TEXT_POLISH_MODEL" | "TEXT_POLISH_ENABLED" | "VIDEO_BUFFER_TARGET" | "VIDEO_ARCHIVE_LIMIT" | "PLAYBACK_RECENCY_WINDOW" | "CHAT_SNAPSHOT_LIMIT" | "CHAT_PAGE_LIMIT" | "QUEUE_SNAPSHOT_LIMIT" | "MAX_PAID_GENERATIONS_PER_DAY" | "MAX_CONCURRENT_GENERATIONS" | "GENERATION_POLL_INTERVAL_SECONDS" | "CHANNEL_BOT_ENABLED" | "CHANNEL_BOT_GROK_ENABLED" | "CHANNEL_BOT_FREE_MODEL" | "CHANNEL_BOT_FREE_MODEL_EVERY" | "CHANNEL_BOT_INTERVAL_MINUTES" | "CHANNEL_BOT_QUEUE_TARGET" | "D1_EMERGENCY_READONLY_UNTIL">> {}
}
