/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: ad64fd7dc22fe2ae7cd35f677136dfb9)
interface __BaseEnv_Env {
	VIDEO_MEDIA: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	ORANGE_API_BASE: "https://api.orangeapi.chat/v1";
	ORANGE_MODEL: "happyhorse-1.0-t2v";
	ORANGE_DURATION_SECONDS: "3";
	ORANGE_RESOLUTION: "720P";
	ORANGE_RATIO: "16:9";
	ORANGE_WATERMARK: "true";
	VIDEO_BUFFER_TARGET: "8";
	VIDEO_ARCHIVE_LIMIT: "160";
	CHAT_SNAPSHOT_LIMIT: "60";
	CHAT_PAGE_LIMIT: "100";
	MAX_PAID_GENERATIONS_PER_DAY: "100";
	VIDEO_WORKFLOW: Workflow<Parameters<import("./index").VideoGenerationWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORANGE_API_BASE" | "ORANGE_MODEL" | "ORANGE_DURATION_SECONDS" | "ORANGE_RESOLUTION" | "ORANGE_RATIO" | "ORANGE_WATERMARK" | "VIDEO_BUFFER_TARGET" | "VIDEO_ARCHIVE_LIMIT" | "CHAT_SNAPSHOT_LIMIT" | "CHAT_PAGE_LIMIT" | "MAX_PAID_GENERATIONS_PER_DAY">> {}
}
